export { CommesseService } from './services/commesse.service';
export { CommonsService } from './services/commons.service';
export { DatiOperativiService } from './services/dati-operativi.service';
export { LegamiTaskUtenteService } from './services/legami-task-utente.service';
export { OrdiniService } from './services/ordini.service';
export { SegreteriaService } from './services/segreteria.service';
export { StatoAvanzamentoService } from './services/stato-avanzamento.service';
export { TipiTrasfertaService } from './services/tipi-trasferta.service';
export { UtentiService } from './services/utenti.service';
